[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "GUCH4uCVy2x3k88Mwn1j43zShVQXA8SVpZJprCF1cPLL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
